# Generated by Django 5.2.7 on 2025-10-03 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lowongan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('perusahaan', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('tanggal_post', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('program_studi', models.CharField(max_length=100)),
                ('angkatan', models.IntegerField()),
                ('jenis_kelamin', models.CharField(max_length=10)),
                ('email_outlook', models.EmailField(max_length=254)),
                ('kontak_wa', models.CharField(max_length=15)),
                ('bukti_konsultasi', models.FileField(blank=True, null=True, upload_to='bukti/')),
                ('sptjm', models.FileField(blank=True, null=True, upload_to='sptjm/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='portfolio/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LowonganApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], default='pending', max_length=20)),
                ('lowongan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop_app.lowongan')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop_app.mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='LaporanKemajuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_perusahaan', models.TextField()),
                ('jobdesk', models.TextField()),
                ('suasana_kerja', models.TextField()),
                ('pembelajaran_berguna', models.TextField()),
                ('kebutuhan_perusahaan', models.TextField()),
                ('bulan', models.PositiveIntegerField()),
                ('tanggal_submit', models.DateTimeField(auto_now_add=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop_app.mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='LaporanAkhir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ringkasan', models.TextField(blank=True, null=True)),
                ('file_laporan', models.FileField(blank=True, null=True, upload_to='laporan_akhir/')),
                ('tanggal_submit', models.DateTimeField(auto_now_add=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop_app.mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='KonfirmasiMagang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=100)),
                ('posisi', models.CharField(max_length=100)),
                ('nama_perusahaan', models.CharField(max_length=200)),
                ('alamat_perusahaan', models.TextField()),
                ('bidang_usaha', models.CharField(max_length=200)),
                ('nama_supervisor', models.CharField(max_length=150)),
                ('email_supervisor', models.EmailField(max_length=254)),
                ('wa_supervisor', models.CharField(blank=True, max_length=20, null=True)),
                ('surat_konfirmasi', models.FileField(upload_to='magang/')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], default='pending', max_length=10)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop_app.mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_terbit', models.DateTimeField(default=django.utils.timezone.now)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('konfirmasi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coop_app.konfirmasimagang')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coop_app.mahasiswa')),
            ],
        ),
    ]
