# Generated by Django 5.2.7 on 2025-10-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0002_drfdosen_drfmahasiswa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drfpost',
            options={'ordering': ['uploaded']},
        ),
        migrations.RenameField(
            model_name='drfpost',
            old_name='upload',
            new_name='uploaded',
        ),
        migrations.AddField(
            model_name='drfpost',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='drfpost',
            name='rating',
            field=models.CharField(choices=[('excellent', 1), ('average', 0), ('bad', -1)], default='average'),
        ),
    ]
